// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type HealthCheckResp struct {
	Appstatus string `json:"appstatus"`
	Rdsstatus string `json:"rdsstatus"`
	Kvstatus  string `json:"kvstatus"`
}
