// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	serveractuator "github.com/wordpress-plus/api-app/internal/handler/server/actuator"
	"github.com/wordpress-plus/api-app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/add-collection",
				Handler: serveractuator.HealthCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/actuator/health"),
	)
}
