// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	serveractuator "github.com/wordpress-plus/app-api/internal/handler/server/actuator"
	"github.com/wordpress-plus/app-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: serveractuator.HealthCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/actuator"),
	)
}
