name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get current tag
        id: get_tag
        run: echo "CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set tag suffix if on develop branch
        id: set_suffix
        run: echo "TAG_SUFFIX=$(if [ '${{ env.BRANCH_NAME }}' == 'develop' ]; then echo '-beta'; else echo ''; fi)" >> $GITHUB_ENV

      - name: Create new tag with suffix
        id: create_tag
        run: echo "NEW_TAG=${{ env.CURRENT_TAG }}${{ env.TAG_SUFFIX }}" >> $GITHUB_ENV

      - name: Release
        run: npx changelogithub --tag $NEW_TAG
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
